% Prolog file used for defining workout rules and logic
% Exercises, muscle groups were generated by Claude
% Injury recovery days were as well generated by Claude

% Source : 
% - https://www.swi-prolog.org/pldoc/man?predicate=findall/3
% - https://www.swi-prolog.org/pldoc/man?predicate=max_list/2

% =====================================
% Connection test
% =====================================

connection_test :- write('Workout rules module loaded successfully.'), nl.

% =====================================
% Exercises
% =====================================

exercise('bench press', chest).
exercise('push ups', chest).
exercise('dumbbell fly', chest).
exercise('incline press', chest).

exercise('curls', biceps).
exercise('hammer curls', biceps).
exercise('preacher curls', biceps).

exercise('squats', legs).
exercise('leg press', legs).
exercise('lunges', legs).
exercise('leg curls', legs).
exercise('leg extensions', legs).

exercise('deadlift', back).
exercise('lat pulldown', back).
exercise('pull ups', back).
exercise('rows', back).

exercise('shoulder press', shoulders).
exercise('lateral raises', shoulders).
exercise('front raises', shoulders).

exercise('tricep dips', triceps).
exercise('tricep extensions', triceps).
exercise('close grip press', triceps).

exercise('plank', abdominals).
exercise('crunches', abdominals).
exercise('sit ups', abdominals).

exercise('calf raises', calves).

% =====================================
% Muscle groups
% =====================================

muscle_group(chest).
muscle_group(biceps).
muscle_group(legs).
muscle_group(back).
muscle_group(shoulders).
muscle_group(triceps).
muscle_group(abdominals).
muscle_group(calves).
muscle_group(glutes).

% =====================================
% Rest requirements
% =====================================

% === 1 day ===
rest_day_required(biceps, 1).
rest_day_required(triceps, 1).
rest_day_required(abdominals, 1).
rest_day_required(calves, 1).

% === 2 day ===
rest_day_required(chest, 2).
rest_day_required(back, 2).
rest_day_required(shoulders, 2).
rest_day_required(legs, 2).
rest_day_required(glutes, 2).

% =====================================
% Injury recovery times (in days)
% =====================================

injury_recovery_days(biceps, 14).
injury_recovery_days(triceps, 14).
injury_recovery_days(calves, 14).

injury_recovery_days(abdominals, 21).
injury_recovery_days(shoulders, 21).

injury_recovery_days(chest, 28).
injury_recovery_days(back, 28).
injury_recovery_days(legs, 28).
injury_recovery_days(glutes, 28).

% =====================================
% Muscle groups trained together
% =====================================

trained_together(biceps, triceps).

trained_together(chest, triceps).
trained_together(chest, shoulders).
trained_together(chest, abdominals).

trained_together(shoulders, triceps).
trained_together(shoulders, abdominals).

trained_together(back, biceps).
trained_together(back, abdominals).

trained_together(legs, glutes).
trained_together(legs, calves).
trained_together(legs, abdominals).

trained_together(glutes, calves).
trained_together(glutes, abdominals).

% =====================================
% FastMCP data extraction
% workout_history(Date, Muscle, Exercise, Duration)
% injury(Date, Muscle)
% =====================================

:- dynamic workout_history/4.
:- dynamic injury/2.

% =====================================
% Max rest day requirement from workout_history rest_day_required/2
% =====================================

% Saving all required rest days from workout_history `rest_day_required` function based on `Muscle` in the `RestDays` list.
% findall is used to collect all rest days into a list. In this case, we want to collect RestDay from each Muscle.
workout_rest_days(RestDays):-
    findall(RestDay, (workout_history(_, Muscle, _, _), rest_day_required(Muscle, RestDay)), RestDays).

max_day_required(MaxRestDays):-
    workout_rest_days(RestDays),
    max_list(RestDays, MaxRestDays).

% ====================================
% Date calculation
% The difference bewteen two dates is calculates in seconds
% ====================================

% Calculating the difference between two dates in days
days_between(Date1, Date2, Days):-
    Days is round((Date2 - Date1) / (24 * 60 * 60)).

% Check if sufficient rest has been given to a muscle group
sufficient_rest(Muscle, LastWorkoutDate, CurrentDate):-
    rest_day_required(Muscle, RequiredRestDays),
    days_between(LastWorkoutDate, CurrentDate, DaysBetween),
    DaysBetween >= RequiredRestDays.

% ====================================
% Validation rules
% ====================================

% Check if muscle group has been trained recently
recently_trained(Muscle, Date):-
    workout_history(WorkoutDate, Muscle, _, _),
    days_between(WorkoutDate, Date, Days),
    rest_day_required(Muscle, RequiredRestDays),
    Days < RequiredRestDays.

% Check if there are any injuries for a muscle group
has_injury(Muscle, CurrentDate):-
    injury(InjuryDate, Muscle),
    injury_recovery_days(Muscle, RecoveryDays),
    days_between(InjuryDate, CurrentDate, DaysSinceInjury),
    DaysSinceInjury < RecoveryDays.

% Check if a coomplementary muscle group has been injured and returns it
trained_together_has_injury(Muscle, CurrentDate, InjuredMuscle):-
    (trained_together(Muscle, InjuredMuscle); trained_together(InjuredMuscle, Muscle)),
    has_injury(InjuredMuscle, CurrentDate).

% ====================================
% Rules applying
% ====================================

% Check if an exercise can be performed on a given date

% 1. Check if injured
% ! is used to stop backtracking
can_workout(Muscle, Date, 'injury_present'):-
    has_injury(Muscle, Date).

% 2. Check if a muscle trained together with the target is injured
% the ! to stop backtracking after the first try
can_workout(Muscle, Date, 'trained_together_injured'):-
    trained_together_has_injury(Muscle, Date, _), !.

% 3. Check if recently trained
can_workout(Muscle, Date, 'insufficient_rest'):-
    recently_trained(Muscle, Date).

% 4. Returning true if both checks are passed
% \+ for negation
can_workout(Muscle, Date, 'workout_allowed'):-
    \+ has_injury(Muscle, Date),
    \+ trained_together_has_injury(Muscle, Date, _),
    \+ recently_trained(Muscle, Date).

% ====================================
% Other muscle groups that could be trained instead
% ====================================

alternative_muscle(Muscle, AlternativeMuscle):-
    muscle_group(AlternativeMuscle),
    AlternativeMuscle \= Muscle,
    \+ trained_together(Muscle, AlternativeMuscle).

% If can_workout is not allowed, then it proposes other muscle groups
% once because if all are true, it was suggesting muscles for each validation.
suggest_alternative(Muscle, Date, AlternativeMuscle):-
    once((has_injury(Muscle, Date); trained_together_has_injury(Muscle, Date, _); recently_trained(Muscle, Date))),
    alternative_muscle(Muscle, AlternativeMuscle),
    can_workout(AlternativeMuscle, Date, 'workout_allowed').

% ====================================
% Prolog Reasoning for the LLM answer
% ====================================
suggested_rest_days(MaxRestDays):-
    max_day_required(MaxRestDays).