% Prolog file used for defining workout rules and logic
% Rules have been generated by Claude AI

% =====================================
% Exercises
% =====================================

exercise('bench press', chest).
exercise('push ups', chest).
exercise('curls', biceps).
exercise('squats', legs).
exercise('leg press', legs).
exercise('deadlift', back)
exercise('lat pulldown', back).
exercise('shoulder press', shoulders).
exercise('tricep dips', triceps).
exercise('plank', abdominals).
exercise('lunges', legs).
exercise('calf raises', calves).

% =====================================
% Muscle groups
% =====================================

muscle_group(chest).
muscle_group(biceps).
muscle_group(legs).
muscle_group(back).
muscle_group(shoulders).
muscle_group(triceps).
muscle_group(abdominals).
muscle_group(calves).

% =====================================
% Rest requirements
% =====================================

% === 1 day ===
rest_day_required(biceps, 1).
rest_day_required(triceps, 1).
rest_day_required(abdominals, 1).
rest_day_required(calves, 1).

% === 2 day ===
rest_days_required(chest, 2).
rest_days_required(back, 2).
rest_days_required(shoulders, 2).
rest_days_requried(legs, 2).
rest_days_required(glutes, 2).

% =====================================
% Muscle groups trained together
% =====================================

trained_together(chest, triceps).
trained_together(chest, shoulders).
trained_together(back, biceps).
trained_together(legs, glutes).
trained_together(legs, abdominals).